
FROM golang:1.14-alpine as build-env

RUN apk add --no-cache git

ARG GOPROXY=https://proxy.golang.org,direct
ARG VERSION=v0.0.1

WORKDIR /go/src
RUN git clone https://github.com/knative/eventing.git knative.dev/eventing; 

WORKDIR /go/src/knative.dev/eventing/cmd/in_memory/channel_controller

RUN set -eux; \
    \
	git checkout ${VERSION}; \
    go build -o in-memory-channel-controller; \
    \
    mkdir -p /ko-app; \
    mkdir -p ./kodata; \
    cp -R ./kodata /var/run/ko; \
    cp in-memory-channel-controller /ko-app/;

FROM alpine
COPY --from=build-env /ko-app /ko-app
COPY --from=build-env /var/run/ko /var/run/ko 
ENV PATH="/ko-app:${PATH}" KO_DATA_PATH=/var/run/ko
ENTRYPOINT ["/ko-app/in-memory-channel-controller"]
