
FROM golang:1.14-alpine as build-env

RUN apk add --no-cache git

ARG GOPROXY=https://proxy.golang.org,direct
ARG VERSION=v0.0.1

WORKDIR /go/src
RUN git clone https://github.com/knative/eventing.git knative.dev/eventing; 

WORKDIR /go/src/knative.dev/eventing/cmd/upgrade/v0.15.0

RUN set -eux; \
    \
    go build -o upgrade-v0.15.0; \
    \
    mkdir -p /app; \
    mkdir -p ./kodata; \
    cp -R ./kodata /app/kodata; \
    cp upgrade-v0.15.0 /app/;

FROM alpine
COPY --from=build-env /app /app
ENV KO_DATA_PATH=/app/kodata
CMD ["/app/upgrade-v0.15.0"]
