name: build-operator
on:
  push:
    paths:
      - .github/workflows/build-operator.yml
      - operator/**

jobs:

  build-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: v0.4.1
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: |
          export VERSION=$(cat ./operator/.version);
          docker buildx build \
                --push \
                --build-arg=VERSION=${VERSION} \
                --platform=linux/amd64,linux/arm64 \
                -t querycap/knative-operator:${VERSION} \
                -f operator/Dockerfile.operator .
      - run: rm -rf ${HOME}/.docker/config
